content:
  - name: sections
    label: Sections
    path: src/content/sections
    type: collection
    view:
      fields: [ title, gallery ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: gallery, label: Image Gallery, type: image, options: { multiple: { max: 6 } } }
      - { name: body, label: Body, type: rich-text }
media:
  - name: images
    label: Images
    input: public/images
    output: /public/images
    extensions: [ png, jpg, jpeg ]
